In [2]:
import pandas as pd
import math
import numpy as np

In [3]:
DATA_DIR = '/Users/39388/Downloads/psl_csv2/'

In [4]:

all_data = pd.read_csv(DATA_DIR + 'all_matches.csv')

all_data["total_runs"] = all_data['runs_off_bat'].astype(int) + all_data["extras"]
all_data["runs_conceded_bowler"] = all_data['runs_off_bat'].astype(int) + all_data["wides"] + all_data["noballs"]+ all_data["penalty"]
all_data["wicket_1_0"]= all_data["other_wicket_type"]
all_data['wicket_1_0'] = all_data['player_dismissed'] != '0'


all_data_2020 = all_data[all_data.season.isin(['2019/2020','2020/21'])]
all_data.loc[all_data['start_date'].str.contains('2020'), 'season'] = '2020'
all_data_2020 = all_data[all_data.season.isin(['2020'])]

all_data_2021 = all_data[all_data.season.isin(['2019/2020','2020/21','2021/22'])]
all_data.loc[all_data['start_date'].str.contains('2021'), 'season'] = '2021'
all_data_2021 = all_data[all_data.season.isin(['2021'])]

all_data_2022 = all_data[all_data.season.isin(['2019/2020','2020/21','2021/22','2022'])]
all_data.loc[all_data['start_date'].str.contains('2022'), 'season'] = '2022'
all_data_2022 = all_data[all_data.season.isin(['2022'])]

all_data_2020

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,total_runs,runs_conceded_bowler,wicket_1_0
13173,1211642,2020,2020-02-20,National Stadium,1,0.1,Islamabad United,Quetta Gladiators,C Munro,L Ronchi,...,NaN,NaN,NaN,caught and bowled,C Munro,NaN,NaN,0,NaN,True
13174,1211642,2020,2020-02-20,National Stadium,1,0.2,Islamabad United,Quetta Gladiators,DJ Malan,L Ronchi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,True
13175,1211642,2020,2020-02-20,National Stadium,1,0.3,Islamabad United,Quetta Gladiators,DJ Malan,L Ronchi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,True
13176,1211642,2020,2020-02-20,National Stadium,1,0.4,Islamabad United,Quetta Gladiators,L Ronchi,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,True
13177,1211642,2020,2020-02-20,National Stadium,1,0.5,Islamabad United,Quetta Gladiators,L Ronchi,DJ Malan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33781,1231146,2020,2020-11-17,National Stadium,2,17.6,Karachi Kings,Lahore Qalandars,Imad Wasim,Babar Azam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,True
33782,1231146,2020,2020-11-17,National Stadium,2,18.1,Karachi Kings,Lahore Qalandars,Imad Wasim,Babar Azam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,True
33783,1231146,2020,2020-11-17,National Stadium,2,18.2,Karachi Kings,Lahore Qalandars,Imad Wasim,Babar Azam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,True
33784,1231146,2020,2020-11-17,National Stadium,2,18.3,Karachi Kings,Lahore Qalandars,Babar Azam,Imad Wasim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,True
33785,1231146,2020,2020-11-17,National Stadium,2,18.4,Karachi Kings,Lahore Qalandars,Imad Wasim,Babar Azam,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,True

# Binomial Reg 2020

In [5]:
all_data_2020_logReg = pd.DataFrame()

In [6]:
data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

In [7]:
all_data_2020_logReg = pd.DataFrame(data)

In [8]:
all_data_2020_logReg

        batting_team
0   Lahore Qalandars
1      Karachi Kings
2     Multan Sultans
3     Peshawar Zalmi
4   Islamabad United
5  Quetta Gladiators

In [9]:
all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2020_copy = all_data_2020
all_data_2020_copy = all_data_2020_copy  [all_data_2020_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2020_copy_2 = all_data_2020
all_data_2020_copy_2 = all_data_2020_copy_2  [all_data_2020_copy_2  .ball > 15 ]

# First Six Overs Runs

In [10]:
runs_first_six_overs = all_data_2020_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2020_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2020_logReg = all_data_2020_logReg.drop("runs_first_six_overs",axis=1)

all_data_2020_logReg

        batting_team  runrate_first_six_overs
0   Lahore Qalandars                 7.707216
1      Karachi Kings                 8.147971
2     Multan Sultans                 7.807229
3     Peshawar Zalmi                 7.984000
4   Islamabad United                 8.822485
5  Quetta Gladiators                 7.289552

# Wickets First Six Overs

In [11]:
wickets_lost_six_overs = all_data_2020_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='NaN').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False)

In [ ]:
wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)

In [ ]:
wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

In [ ]:
all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_six_overs, how="left")

In [ ]:
all_data_2020_logReg

# RR Last 5 Overs

In [232]:
runs_last_five_overs = all_data_2020_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2020_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False)

In [233]:
runs_last_five_overs

        batting_team  runs_last_five_overs
2   Lahore Qalandars                   554
1      Karachi Kings                   431
3     Multan Sultans                   419
0   Islamabad United                   342
5  Quetta Gladiators                   298
4     Peshawar Zalmi                   293

In [234]:
balls_faced_last_five_overs

        batting_team  balls_faced_last_five_overs
2   Lahore Qalandars                          317
1      Karachi Kings                          273
3     Multan Sultans                          234
0   Islamabad United                          222
5  Quetta Gladiators                          214
4     Peshawar Zalmi                          208

In [235]:
runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)

In [236]:
run_rate_last_five_overs = runs_last_five_overs

In [237]:
all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_last_five_overs, how="left")

In [238]:
all_data_2020_logReg = all_data_2020_logReg.drop("runs_last_five_overs",axis=1)

In [239]:
all_data_2020_logReg

,batting_team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs
0,Lahore Qalandars,7.707216,53.888889,10.485804
1,Karachi Kings,8.147971,38.090909,9.472527
2,Multan Sultans,7.807229,31.923077,10.743590
3,Peshawar Zalmi,7.984000,34.090909,8.451923
4,Islamabad United,8.822485,33.800000,9.243243
5,Quetta Gladiators,7.289552,37.222222,8.355140

# Wickets Lost Last 5 Overs

In [240]:
wickets_lost_last_five_overs = all_data_2020_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2020_logReg

,batting_team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs
0,Lahore Qalandars,7.707216,53.888889,10.485804,35.222222
1,Karachi Kings,8.147971,38.090909,9.472527,24.818182
2,Multan Sultans,7.807229,31.923077,10.743590,18.000000
3,Peshawar Zalmi,7.984000,34.090909,8.451923,23.111111
4,Islamabad United,8.822485,33.800000,9.243243,20.181818
5,Quetta Gladiators,7.289552,37.222222,8.355140,21.400000

In [241]:
batsman_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Batsman.csv')
bowler_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Bowlers.csv')

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"batting_team": "team"})

all_data_2020_logReg = all_data_2020_logReg.merge(batsman_pca_2020, how="left")

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2020_logReg = all_data_2020_logReg.merge(bowler_pca_2020, how="left")

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "bowler_PCA"})

In [242]:

all_data_2020_logReg["wins"] = 5,5,6,4,3,4
all_data_2020_logReg["total_matches"] = 5,4,2,5,6,5
all_data_2020_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA,wins,total_matches
0,Lahore Qalandars,7.707216,53.888889,10.485804,35.222222,1.136496,1.032883,5,10
1,Karachi Kings,8.147971,38.090909,9.472527,24.818182,-0.705016,-0.723688,5,9
2,Multan Sultans,7.807229,31.923077,10.743590,18.000000,1.236945,-0.503700,6,8
3,Peshawar Zalmi,7.984000,34.090909,8.451923,23.111111,-0.545951,1.792204,4,9
4,Islamabad United,8.822485,33.800000,9.243243,20.181818,-0.245910,0.406583,3,9
5,Quetta Gladiators,7.289552,37.222222,8.355140,21.400000,-0.590680,-0.285363,4,9

# Binomial Reg 2021

In [97]:


all_data_2021_logReg = pd.DataFrame()

data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

all_data_2021_logReg = pd.DataFrame(data)

all_data_2021_logReg

all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2021_copy = all_data_2021
all_data_2021_copy = all_data_2021_copy  [all_data_2021_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2021_copy_2 = all_data_2021
all_data_2021_copy_2 = all_data_2021_copy_2  [all_data_2021_copy_2  .ball > 15 ]


# First Six Overs Runs


runs_first_six_overs = all_data_2021_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2021_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2021_logReg = all_data_2021_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2021_logReg = all_data_2021_logReg.drop("runs_first_six_overs",axis=1)

all_data_2021_logReg

# Wickets First Six Overs 



wickets_lost_six_overs = all_data_2021_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False) 



wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)


wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

all_data_2021_logReg = all_data_2021_logReg.merge(wickets_lost_six_overs, how="left")

all_data_2021_logReg

# RR Last 5 Overs


runs_last_five_overs = all_data_2021_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2021_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False) 





runs_last_five_overs

balls_faced_last_five_overs

runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_last_five_overs = runs_last_five_overs

all_data_2021_logReg = all_data_2021_logReg.merge(run_rate_last_five_overs, how="left")

all_data_2021_logReg = all_data_2021_logReg.drop("runs_last_five_overs",axis=1)

all_data_2021_logReg

# Wickets Lost Last 5 Overs

wickets_lost_last_five_overs = all_data_2021_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2021_logReg = all_data_2021_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2021_logReg


batsman_pca_2021 = pd.read_csv('/Users/39388/Documents/PCA_2021_Batsman.csv')
bowler_pca_2021 = pd.read_csv('/Users/39388/Documents/PCA_2021_Bowlers.csv')

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"batting_team": "team"})

all_data_2021_logReg = all_data_2021_logReg.merge(batsman_pca_2021, how="left")

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2021_logReg = all_data_2021_logReg.merge(bowler_pca_2021, how="left")

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"PC1": "bowler_PCA"})


all_data_2021_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,6.306452,1.818182,9.227437,1.777778,-0.265988,0.913552
1,Karachi Kings,7.116945,1.363636,9.975904,2.454545,0.998724,-0.467547
2,Multan Sultans,8.323851,1.222222,10.006515,3.111111,0.678627,-0.137041
3,Peshawar Zalmi,7.955654,1.538462,10.656716,1.923077,-0.159425,-0.480023
4,Islamabad United,7.911290,2.666667,9.921429,1.800000,0.006476,0.612931
5,Quetta Gladiators,6.848000,1.500000,9.672414,2.272727,-1.002585,-0.075798

# Binomial Reg 2022

In [117]:


all_data_2022_logReg = pd.DataFrame()

data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

all_data_2022_logReg = pd.DataFrame(data)

all_data_2022_logReg

all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2022_copy = all_data_2022
all_data_2022_copy = all_data_2022_copy  [all_data_2022_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2022_copy_2 = all_data_2022
all_data_2022_copy_2 = all_data_2022_copy_2  [all_data_2022_copy_2  .ball > 15 ]


# First Six Overs Runs


runs_first_six_overs = all_data_2022_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2022_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2022_logReg = all_data_2022_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2022_logReg = all_data_2022_logReg.drop("runs_first_six_overs",axis=1)

all_data_2022_logReg

# Wickets First Six Overs 



wickets_lost_six_overs = all_data_2022_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False) 



wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)


wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

all_data_2022_logReg = all_data_2022_logReg.merge(wickets_lost_six_overs, how="left")

all_data_2022_logReg

# RR Last 5 Overs


runs_last_five_overs = all_data_2022_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2022_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False) 





runs_last_five_overs

balls_faced_last_five_overs

runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_last_five_overs = runs_last_five_overs

all_data_2022_logReg = all_data_2022_logReg.merge(run_rate_last_five_overs, how="left")

all_data_2022_logReg = all_data_2022_logReg.drop("runs_last_five_overs",axis=1)

all_data_2022_logReg

# Wickets Lost Last 5 Overs

wickets_lost_last_five_overs = all_data_2022_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2022_logReg = all_data_2022_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2022_logReg


batsman_pca_2022 = pd.read_csv('/Users/39388/Documents/PCA_2022_Batsman.csv')
bowler_pca_2022 = pd.read_csv('/Users/39388/Documents/PCA_2022_Bowlers.csv')

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"batting_team": "team"})

all_data_2022_logReg = all_data_2022_logReg.merge(batsman_pca_2022, how="left")

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2022_logReg = all_data_2022_logReg.merge(bowler_pca_2022, how="left")

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"PC1": "bowler_PCA"})


all_data_2022_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,8.671141,1.636364,11.180412,2.545455,1.136496,1.032883
1,Karachi Kings,6.847826,1.272727,8.400000,2.230769,-0.705016,-0.150896
2,Multan Sultans,7.837838,1.111111,11.566474,2.800000,1.236945,2.170999
3,Peshawar Zalmi,8.446602,1.384615,9.543860,2.727273,-0.545951,1.792204
4,Islamabad United,8.716049,2.111111,9.000000,3.333333,-0.245910,0.504455
5,Quetta Gladiators,9.064516,1.400000,9.585938,2.666667,-0.590680,0.006082

# Binomial Reg

In [243]:
import statsmodels.api as sm

import pandas

from patsy import dmatrices
all_data_2020_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA,wins,total_matches
0,Lahore Qalandars,7.707216,53.888889,10.485804,35.222222,1.136496,1.032883,5,10
1,Karachi Kings,8.147971,38.090909,9.472527,24.818182,-0.705016,-0.723688,5,9
2,Multan Sultans,7.807229,31.923077,10.743590,18.000000,1.236945,-0.503700,6,8
3,Peshawar Zalmi,7.984000,34.090909,8.451923,23.111111,-0.545951,1.792204,4,9
4,Islamabad United,8.822485,33.800000,9.243243,20.181818,-0.245910,0.406583,3,9
5,Quetta Gladiators,7.289552,37.222222,8.355140,21.400000,-0.590680,-0.285363,4,9

In [259]:
y, X = dmatrices('wins + total_matches  ~  batsman_PCA',\
                 data=all_data_2020_logReg, return_type='dataframe')

In [260]:
glm_binom = sm.GLM(y, X, family=sm.families.Binomial())
res = glm_binom.fit()
print(res.summary())

                     Generalized Linear Model Regression Results
=====================================================================================
Dep. Variable:     ['wins', 'total_matches']   No. Observations:                    6
Model:                                   GLM   Df Residuals:                        4
Model Family:                       Binomial   Df Model:                            1
Link Function:                         Logit   Scale:                          1.0000
Method:                                 IRLS   Log-Likelihood:                -9.2378
Date:                       Tue, 23 Aug 2022   Deviance:                      0.72665
Time:                               20:54:33   Pearson chi2:                    0.720
No. Iterations:                            4   Pseudo R-squ. (CS):            0.05351
Covariance Type:                   nonrobust
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -0.7096      0.239     -2.974      0.003      -1.177      -0.242
batsman_PCA     0.1614      0.280      0.576      0.565      -0.388       0.711
===============================================================================

Collecting firthlogist
  Downloading firthlogist-0.5.0-py3-none-any.whl (527 kB)
     |████████████████████████████████| 527 kB 1.3 MB/s eta 0:00:01
Collecting tabulate<0.9.0,>=0.8.10
  Downloading tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting scikit-learn<2.0.0,>=1.1.1
  Downloading scikit_learn-1.1.2-cp39-cp39-macosx_10_9_x86_64.whl (8.7 MB)
     |████████████████████████████████| 8.7 MB 1.3 MB/s eta 0:00:01
Collecting numpy<2.0.0,>=1.22.4
  Downloading numpy-1.23.2-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
     |████████████████████████████████| 18.1 MB 104 kB/s eta 0:00:01
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/39388/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.1.1->firthlogist) (2.2.0)
Requirement already satisfied: joblib>=1.0.0 in /Users/39388/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.1.1->firthlogist) (1.1.0)
Requirement already satisfied: scipy>=1.3.2 in /Users/39388/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn<2.0.0,>=1.1.1->firthlogist) (1.7.3)
  Downloading numpy-1.22.4-cp39-cp39-macosx_10_15_x86_64.whl (17.7 MB)
     |████████████████████████████████| 17.7 MB 272 kB/s eta 0:00:01    |██▌                             | 1.4 MB 60 kB/s eta 0:04:32     |███████████▍                    | 6.3 MB 391 kB/s eta 0:00:30     |████████████████████████████▊   | 15.9 MB 236 kB/s eta 0:00:08
Installing collected packages: numpy, tabulate, scikit-learn, firthlogist
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
  Attempting uninstall: tabulate
    Found existing installation: tabulate 0.8.9
    Uninstalling tabulate-0.8.9:
      Successfully uninstalled tabulate-0.8.9
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
pymc3 3.11.5 requires numpy<1.22.2,>=1.15.0, but you have numpy 1.22.4 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.22.4 which is incompatible.
Successfully installed firthlogist-0.5.0 numpy-1.22.4 scikit-learn-1.1.2 tabulate-0.8.10

In [249]:
import pandas as pd
import numpy as np
def firth_logit(X,y,num_iter=5000,learning_rate=0.01):
    #Initialize weights
    weights = np.ones(X.shape[1])
    
    #Define get_predictions function
    def get_predictions(X,weights):
        z = np.dot(X,weights)
        y_pred =  1/(1 + np.exp(-z))
    #Perform gradient descent
    for i in range(num_iter):
        
        y_pred = get_predictions(X,weights)
        
        #Calculate Fisher information matrix
        Xt = X.transpose()
        W = np.diag(y_pred*(1-y_pred))
        I = np.linalg.multi_dot([Xt,W,X])
        
        #Find diagonal of Hat Matrix
        sqrtW = W**0.5
        H = np.linalg.multi_dot([sqrtW,X,np.linalg.inv(I),Xt,sqrtW])
        hat_diag = np.diag(H)
        
        #Calculate U_star
        U_star = np.matmul((y -y_pred + hat_diag*(0.5 - y_pred)),X)
        
        #Update weights
        weights += np.matmul(np.linalg.inv(I),U_star)*learning_rate
    
    #Get final predictions
    y_pred =  get_predictions(X,weights)
    return y_pred

In [250]:
firth_logit(X,y,num_iter=5000,learning_rate=0.01)

TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

In [252]:
def firth_likelihood(beta, logit):
    return -(logit.loglike(beta) + 0.5*np.log(np.linalg.det(-logit.hessian(beta))))

# Do firth regression
# Note information = -hessian, for some reason available but not implemented in statsmodels
def fit_firth(y, X, start_vec=None, step_limit=1000, convergence_limit=0.0001):

    logit_model = smf.Logit(y, X)
    
    if start_vec is None:
        start_vec = np.zeros(X.shape[1])
    
    beta_iterations = []
    beta_iterations.append(start_vec)
    for i in range(0, step_limit):
        pi = logit_model.predict(beta_iterations[i])
        W = np.diagflat(np.multiply(pi, 1-pi))
        var_covar_mat = np.linalg.pinv(-logit_model.hessian(beta_iterations[i]))

        # build hat matrix
        rootW = np.sqrt(W)
        H = np.dot(np.transpose(X), np.transpose(rootW))
        H = np.matmul(var_covar_mat, H)
        H = np.matmul(np.dot(rootW, X), H)

        # penalised score
        U = np.matmul(np.transpose(X), y - pi + np.multiply(np.diagonal(H), 0.5 - pi))
        new_beta = beta_iterations[i] + np.matmul(var_covar_mat, U)

        # step halving
        j = 0
        while firth_likelihood(new_beta, logit_model) > firth_likelihood(beta_iterations[i], logit_model):
            new_beta = beta_iterations[i] + 0.5*(new_beta - beta_iterations[i])
            j = j + 1
            if (j > step_limit):
                sys.stderr.write('Firth regression failed\n')
                return None

        beta_iterations.append(new_beta)
        if i > 0 and (np.linalg.norm(beta_iterations[i] - beta_iterations[i-1]) < convergence_limit):
            break

    return_fit = None
    if np.linalg.norm(beta_iterations[i] - beta_iterations[i-1]) >= convergence_limit:
        sys.stderr.write('Firth regression failed\n')
    else:
        # Calculate stats
        fitll = -firth_likelihood(beta_iterations[-1], logit_model)
        intercept = beta_iterations[-1][0]
        beta = beta_iterations[-1][1:].tolist()
        bse = np.sqrt(np.diagonal(np.linalg.pinv(-logit_model.hessian(beta_iterations[-1]))))
        
        return_fit = intercept, beta, bse, fitll

    return return_fit

if __name__ == "__main__":

    import sys
    import warnings
    import math
    import statsmodels
    import numpy as np
    from scipy import stats
    import statsmodels.api as smf
  
    # create X and y here. Make sure X has an intercept term (column of ones)
    # ...

    # How to call and calculate p-values
    (intercept, beta, bse, fitll) = fit_firth(y, X)
    beta = [intercept] + beta
    
    # Wald test
    waldp = []
    for beta_val, bse_val in zip(beta, bse):
        waldp.append(2 * (1 - stats.norm.cdf(abs(beta_val/bse_val))))

    # LRT
    lrtp = []
    for beta_idx, (beta_val, bse_val) in enumerate(zip(beta, bse)):
        null_X = np.delete(X, beta_idx, axis=1)
        (null_intercept, null_beta, null_bse, null_fitll) = fit_firth(y, null_X)
        lrstat = -2*(null_fitll - fitll)
        lrt_pvalue = 1
        if lrstat > 0: # non-convergence
            lrt_pvalue = stats.chi2.sf(lrstat, 1)
        lrtp.append(lrt_pvalue)

ValueError: endog must be in the unit interval.