In [2]:
import pandas as pd
import math
import numpy as np

In [271]:
DATA_DIR = '/Users/39388/Downloads/'

In [272]:
all_data = pd.read_csv(DATA_DIR + 'all_matches_modified.csv')

all_data["total_runs"] = all_data['runs_off_bat'].astype(int) + all_data["extras"]
all_data["runs_conceded_bowler"] = all_data['runs_off_bat'].astype(int) + all_data["wides"] + all_data["noballs"]+ all_data["penalty"]
all_data["wicket_1_0"]= all_data["other_wicket_type"]
all_data['wicket_1_0'] = all_data['player_dismissed'] != '0'


all_data_2020 = all_data[all_data.season.isin(['2019/2020','2020/21'])]
all_data.loc[all_data['start_date'].str.contains('2020'), 'season'] = '2020'
all_data_2020 = all_data[all_data.season.isin(['2020'])]

all_data_2021 = all_data[all_data.season.isin(['2019/2020','2020/21','2021/22'])]
all_data.loc[all_data['start_date'].str.contains('2021'), 'season'] = '2021'
all_data_2021 = all_data[all_data.season.isin(['2021'])]

all_data_2022 = all_data[all_data.season.isin(['2019/2020','2020/21','2021/22','2022'])]
all_data.loc[all_data['start_date'].str.contains('2022'), 'season'] = '2022'
all_data_2022 = all_data[all_data.season.isin(['2022'])]

all_data_2020

,Unnamed: 0,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,...,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,is_four,is_six,total_runs,runs_conceded_bowler,wicket_1_0
13173,13173,1211642,2020,2020-02-20,National Stadium,1,0.1,Islamabad United,Quetta Gladiators,C Munro,...,0.0,caught and bowled,C Munro,0.0,0.0,False,False,0,0.0,True
13174,13174,1211642,2020,2020-02-20,National Stadium,1,0.2,Islamabad United,Quetta Gladiators,DJ Malan,...,0.0,0,0,0.0,0.0,False,False,0,0.0,False
13175,13175,1211642,2020,2020-02-20,National Stadium,1,0.3,Islamabad United,Quetta Gladiators,DJ Malan,...,0.0,0,0,0.0,0.0,False,False,1,1.0,False
13176,13176,1211642,2020,2020-02-20,National Stadium,1,0.4,Islamabad United,Quetta Gladiators,L Ronchi,...,0.0,0,0,0.0,0.0,True,False,4,4.0,False
13177,13177,1211642,2020,2020-02-20,National Stadium,1,0.5,Islamabad United,Quetta Gladiators,L Ronchi,...,0.0,0,0,0.0,0.0,False,False,0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33781,33781,1231146,2020,2020-11-17,National Stadium,2,17.6,Karachi Kings,Lahore Qalandars,Imad Wasim,...,0.0,0,0,0.0,0.0,False,False,1,1.0,False
33782,33782,1231146,2020,2020-11-17,National Stadium,2,18.1,Karachi Kings,Lahore Qalandars,Imad Wasim,...,0.0,0,0,0.0,0.0,False,False,0,0.0,False
33783,33783,1231146,2020,2020-11-17,National Stadium,2,18.2,Karachi Kings,Lahore Qalandars,Imad Wasim,...,0.0,0,0,0.0,0.0,False,False,1,1.0,False
33784,33784,1231146,2020,2020-11-17,National Stadium,2,18.3,Karachi Kings,Lahore Qalandars,Babar Azam,...,0.0,0,0,0.0,0.0,False,False,1,1.0,False
33785,33785,1231146,2020,2020-11-17,National Stadium,2,18.4,Karachi Kings,Lahore Qalandars,Imad Wasim,...,0.0,0,0,0.0,0.0,True,False,4,4.0,False

# Binomial Reg 2020

In [273]:
all_data_2020_logReg = pd.DataFrame()

In [274]:
data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

In [275]:
all_data_2020_logReg = pd.DataFrame(data)

In [276]:
all_data_2020_logReg

        batting_team
0   Lahore Qalandars
1      Karachi Kings
2     Multan Sultans
3     Peshawar Zalmi
4   Islamabad United
5  Quetta Gladiators

In [277]:
all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2020_copy = all_data_2020
all_data_2020_copy = all_data_2020_copy  [all_data_2020_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2020_copy_2 = all_data_2020
all_data_2020_copy_2 = all_data_2020_copy_2  [all_data_2020_copy_2  .ball > 15 ]

# First Six Overs Runs

In [278]:
runs_first_six_overs = all_data_2020_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2020_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2020_logReg = all_data_2020_logReg.drop("runs_first_six_overs",axis=1)

all_data_2020_logReg

        batting_team  runrate_first_six_overs
0   Lahore Qalandars                 7.707216
1      Karachi Kings                 8.147971
2     Multan Sultans                 7.807229
3     Peshawar Zalmi                 7.984000
4   Islamabad United                 8.822485
5  Quetta Gladiators                 7.289552

# Wickets First Six Overs

In [279]:
wickets_lost_six_overs = all_data_2020_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False)

In [280]:
wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)

In [281]:
wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

In [282]:
all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_six_overs, how="left")

In [283]:
all_data_2020_logReg

        batting_team  runrate_first_six_overs  avg_wickets_lost_six_overs
0   Lahore Qalandars                 7.707216                    1.307692
1      Karachi Kings                 8.147971                    1.600000
2     Multan Sultans                 7.807229                    1.727273
3     Peshawar Zalmi                 7.984000                    2.444444
4   Islamabad United                 8.822485                    1.555556
5  Quetta Gladiators                 7.289552                    1.545455

# RR Last 5 Overs

In [284]:
runs_last_five_overs = all_data_2020_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2020_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False)

In [285]:
runs_last_five_overs

        batting_team  runs_last_five_overs
2   Lahore Qalandars                   554
1      Karachi Kings                   431
3     Multan Sultans                   419
0   Islamabad United                   342
5  Quetta Gladiators                   298
4     Peshawar Zalmi                   293

In [286]:
balls_faced_last_five_overs

        batting_team  balls_faced_last_five_overs
2   Lahore Qalandars                          317
1      Karachi Kings                          273
3     Multan Sultans                          234
0   Islamabad United                          222
5  Quetta Gladiators                          214
4     Peshawar Zalmi                          208

In [287]:
runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)

In [288]:
run_rate_last_five_overs = runs_last_five_overs

In [289]:
all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_last_five_overs, how="left")

In [290]:
all_data_2020_logReg = all_data_2020_logReg.drop("runs_last_five_overs",axis=1)

In [291]:
all_data_2020_logReg

,batting_team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs
0,Lahore Qalandars,7.707216,1.307692,10.485804
1,Karachi Kings,8.147971,1.600000,9.472527
2,Multan Sultans,7.807229,1.727273,10.743590
3,Peshawar Zalmi,7.984000,2.444444,8.451923
4,Islamabad United,8.822485,1.555556,9.243243
5,Quetta Gladiators,7.289552,1.545455,8.355140

# Wickets Lost Last 5 Overs

In [292]:
wickets_lost_last_five_overs = all_data_2020_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2020_logReg

,batting_team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs
0,Lahore Qalandars,7.707216,1.307692,10.485804,1.384615
1,Karachi Kings,8.147971,1.600000,9.472527,2.666667
2,Multan Sultans,7.807229,1.727273,10.743590,1.545455
3,Peshawar Zalmi,7.984000,2.444444,8.451923,2.181818
4,Islamabad United,8.822485,1.555556,9.243243,1.666667
5,Quetta Gladiators,7.289552,1.545455,8.355140,1.600000

In [293]:
batsman_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Batsman.csv')
bowler_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Bowlers.csv')

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"batting_team": "team"})

all_data_2020_logReg = all_data_2020_logReg.merge(batsman_pca_2020, how="left")

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2020_logReg = all_data_2020_logReg.merge(bowler_pca_2020, how="left")

all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "bowler_PCA"})

In [294]:

all_data_2020_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,7.707216,1.307692,10.485804,1.384615,1.136496,1.032883
1,Karachi Kings,8.147971,1.600000,9.472527,2.666667,-0.705016,-0.723688
2,Multan Sultans,7.807229,1.727273,10.743590,1.545455,1.236945,-0.503700
3,Peshawar Zalmi,7.984000,2.444444,8.451923,2.181818,-0.545951,1.792204
4,Islamabad United,8.822485,1.555556,9.243243,1.666667,-0.245910,0.406583
5,Quetta Gladiators,7.289552,1.545455,8.355140,1.600000,-0.590680,-0.285363

# Binomial Reg 2021

In [97]:
n = 500

while n > 0:
    
    try: 
        

all_data_2021_logReg = pd.DataFrame()

data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

all_data_2021_logReg = pd.DataFrame(data)

all_data_2021_logReg

all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2021_copy = all_data_2021
all_data_2021_copy = all_data_2021_copy  [all_data_2021_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2021_copy_2 = all_data_2021
all_data_2021_copy_2 = all_data_2021_copy_2  [all_data_2021_copy_2  .ball > 15 ]


# First Six Overs Runs


runs_first_six_overs = all_data_2021_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2021_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2021_logReg = all_data_2021_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2021_logReg = all_data_2021_logReg.drop("runs_first_six_overs",axis=1)

all_data_2021_logReg

# Wickets First Six Overs 



wickets_lost_six_overs = all_data_2021_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False) 



wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)


wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

all_data_2021_logReg = all_data_2021_logReg.merge(wickets_lost_six_overs, how="left")

all_data_2021_logReg

# RR Last 5 Overs


runs_last_five_overs = all_data_2021_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2021_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False) 





runs_last_five_overs

balls_faced_last_five_overs

runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_last_five_overs = runs_last_five_overs

all_data_2021_logReg = all_data_2021_logReg.merge(run_rate_last_five_overs, how="left")

all_data_2021_logReg = all_data_2021_logReg.drop("runs_last_five_overs",axis=1)

all_data_2021_logReg

# Wickets Lost Last 5 Overs

wickets_lost_last_five_overs = all_data_2021_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2021_logReg = all_data_2021_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2021_logReg


batsman_pca_2021 = pd.read_csv('/Users/39388/Documents/PCA_2021_Batsman.csv')
bowler_pca_2021 = pd.read_csv('/Users/39388/Documents/PCA_2021_Bowlers.csv')

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"batting_team": "team"})

all_data_2021_logReg = all_data_2021_logReg.merge(batsman_pca_2021, how="left")

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2021_logReg = all_data_2021_logReg.merge(bowler_pca_2021, how="left")

all_data_2021_logReg= all_data_2021_logReg.rename(columns={"PC1": "bowler_PCA"})


all_data_2021_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,6.306452,1.818182,9.227437,1.777778,-0.265988,0.913552
1,Karachi Kings,7.116945,1.363636,9.975904,2.454545,0.998724,-0.467547
2,Multan Sultans,8.323851,1.222222,10.006515,3.111111,0.678627,-0.137041
3,Peshawar Zalmi,7.955654,1.538462,10.656716,1.923077,-0.159425,-0.480023
4,Islamabad United,7.911290,2.666667,9.921429,1.800000,0.006476,0.612931
5,Quetta Gladiators,6.848000,1.500000,9.672414,2.272727,-1.002585,-0.075798

# Binomial Reg 2022

In [98]:


all_data_2022_logReg = pd.DataFrame()

data = {'batting_team': ['Lahore Qalandars', 'Karachi Kings', 'Multan Sultans', 'Peshawar Zalmi','Islamabad United','Quetta Gladiators']}

all_data_2022_logReg = pd.DataFrame(data)

all_data_2022_logReg

all_data_copy = all_data
all_data_copy = all_data_copy [all_data_copy .ball < 6.1]
all_data_2022_copy = all_data_2022
all_data_2022_copy = all_data_2022_copy  [all_data_2022_copy  .ball < 6.1]

all_data_copy_2 = all_data
all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
all_data_2022_copy_2 = all_data_2022
all_data_2022_copy_2 = all_data_2022_copy_2  [all_data_2022_copy_2  .ball > 15 ]


# First Six Overs Runs


runs_first_six_overs = all_data_2022_copy.groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





balls_faced_first_six_overs = all_data_2022_copy  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_first_six_overs = runs_first_six_overs

all_data_2022_logReg = all_data_2022_logReg.merge(run_rate_first_six_overs, how="left")

all_data_2022_logReg = all_data_2022_logReg.drop("runs_first_six_overs",axis=1)

all_data_2022_logReg

# Wickets First Six Overs 



wickets_lost_six_overs = all_data_2022_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False) 



wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)


wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

all_data_2022_logReg = all_data_2022_logReg.merge(wickets_lost_six_overs, how="left")

all_data_2022_logReg

# RR Last 5 Overs


runs_last_five_overs = all_data_2022_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
.reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





balls_faced_last_five_overs = all_data_2022_copy_2  .groupby(["batting_team"])["ball"].count() \
.reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False) 





runs_last_five_overs

balls_faced_last_five_overs

runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)


run_rate_last_five_overs = runs_last_five_overs

all_data_2022_logReg = all_data_2022_logReg.merge(run_rate_last_five_overs, how="left")

all_data_2022_logReg = all_data_2022_logReg.drop("runs_last_five_overs",axis=1)

all_data_2022_logReg

# Wickets Lost Last 5 Overs

wickets_lost_last_five_overs = all_data_2022_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
.reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

all_data_2022_logReg = all_data_2022_logReg.merge(wickets_lost_last_five_overs, how="left")

all_data_2022_logReg


batsman_pca_2022 = pd.read_csv('/Users/39388/Documents/PCA_2022_Batsman.csv')
bowler_pca_2022 = pd.read_csv('/Users/39388/Documents/PCA_2022_Bowlers.csv')

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"batting_team": "team"})

all_data_2022_logReg = all_data_2022_logReg.merge(batsman_pca_2022, how="left")

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"PC1": "batsman_PCA"})

all_data_2022_logReg = all_data_2022_logReg.merge(bowler_pca_2022, how="left")

all_data_2022_logReg= all_data_2022_logReg.rename(columns={"PC1": "bowler_PCA"})


all_data_2022_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,8.671141,1.636364,11.180412,2.545455,1.136496,1.032883
1,Karachi Kings,6.847826,1.272727,8.400000,2.230769,-0.705016,-0.150896
2,Multan Sultans,7.837838,1.111111,11.566474,2.800000,1.236945,2.170999
3,Peshawar Zalmi,8.446602,1.384615,9.543860,2.727273,-0.545951,1.792204
4,Islamabad United,8.716049,2.111111,9.000000,3.333333,-0.245910,0.504455
5,Quetta Gladiators,9.064516,1.400000,9.585938,2.666667,-0.590680,0.006082

In [295]:
import statsmodels.api as sm

import pandas

from patsy import dmatrices
all_data_2020_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA
0,Lahore Qalandars,7.707216,1.307692,10.485804,1.384615,1.136496,1.032883
1,Karachi Kings,8.147971,1.600000,9.472527,2.666667,-0.705016,-0.723688
2,Multan Sultans,7.807229,1.727273,10.743590,1.545455,1.236945,-0.503700
3,Peshawar Zalmi,7.984000,2.444444,8.451923,2.181818,-0.545951,1.792204
4,Islamabad United,8.822485,1.555556,9.243243,1.666667,-0.245910,0.406583
5,Quetta Gladiators,7.289552,1.545455,8.355140,1.600000,-0.590680,-0.285363

In [310]:
all_data_2020_logReg["wins"] = 5,5,6,4,3,4
all_data_2020_logReg["total_matches"] = 10,9,8,9,9,9
all_data_2020_logReg

,team,runrate_first_six_overs,avg_wickets_lost_six_overs,runrate_last_five_overs,avg_wickets_lost_last_five_overs,batsman_PCA,bowler_PCA,wins,losses,total_matches
0,Lahore Qalandars,7.707216,1.307692,10.485804,1.384615,1.136496,1.032883,5,5,10
1,Karachi Kings,8.147971,1.600000,9.472527,2.666667,-0.705016,-0.723688,5,4,9
2,Multan Sultans,7.807229,1.727273,10.743590,1.545455,1.236945,-0.503700,6,2,8
3,Peshawar Zalmi,7.984000,2.444444,8.451923,2.181818,-0.545951,1.792204,4,5,9
4,Islamabad United,8.822485,1.555556,9.243243,1.666667,-0.245910,0.406583,3,6,9
5,Quetta Gladiators,7.289552,1.545455,8.355140,1.600000,-0.590680,-0.285363,4,5,9

In [316]:
y, X = dmatrices('wins + losses  ~   runrate_first_six_overs + avg_wickets_lost_six_overs + bowler_PCA + batsman_PCA',\
                 data=all_data_2020_logReg, return_type='dataframe')

In [317]:
glm_binom = sm.GLM(y, X, family=sm.families.Binomial())
res = glm_binom.fit()
print(res.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:     ['wins', 'losses']   No. Observations:                    6
Model:                            GLM   Df Residuals:                        1
Model Family:                Binomial   Df Model:                            4
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -8.0484
Date:                Tue, 23 Aug 2022   Deviance:                      0.28582
Time:                        21:15:04   Pearson chi2:                    0.285
No. Iterations:                     4   Pseudo R-squ. (CS):             0.4095
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -0.0818      5.202     -0.016      0.987     -10.277      10.114
runrate_first_six_overs       -0.2046      0.607     -0.337      0.736      -1.394       0.985
avg_wickets_lost_six_overs     1.1022      1.056      1.044      0.296      -0.967       3.171
bowler_PCA                    -0.5122      0.400     -1.280      0.201      -1.297       0.272
batsman_PCA                    0.5711      0.433      1.319      0.187      -0.278       1.420
==============================================================================================

In [34]:
import os

path = '/Users/39388/Downloads/psl_csv2/psl_csv_2020/' #replace with the relative folder to where the files are contained

cwd = os.path.relpath(path) 
files = os.listdir(cwd)  

all_matches_list_2020 = pd.DataFrame()
data = pd.DataFrame()
all_data_2020_logReg = pd.DataFrame()


data_2020_info = pd.DataFrame()

for file in files:
    if file.endswith('info.csv'):
        
        data_2020_temp = pd.DataFrame()
        
        data_2020_temp = pd.read_csv('{}{}'.format(((path,file))),ignore_index=True,on_bad_lines='skip')
        
        data_2020_temp = data_2020_temp.transpose()
        
        data_2020_temp.columns=  data_2020_temp. iloc[0]

        data_2020_temp = data_2020_temp[['winner','match_number']]

        data_2020_temp = data_2020_temp.iloc[1:]

        data_2020_info = data_2020_info.append((data_2020_temp), ignore_index=True, on_bad_lines='skip')

        data_2020_temp = pd.DataFrame()
                                     
        
        
    elif file.endswith('.csv'):
        data_20_info = pd.DataFrame()
        data_20_temp = pd.read_csv('{}{}'.format(((path,file))),ignore_index=True,on_bad_lines='skip')
                                   
        data_2020_copy = data_20_temp
        data_2020_copy = data_2020_copy [data_2020_copy  .ball < 6.1]

        all_data_copy_2 = data_20_temp
        all_data_copy_2 = all_data_copy_2 [all_data_copy_2 .ball > 15]
        all_data_2020_copy_2 = data_20_temp
        all_data_2020_copy_2 = all_data_2020_copy_2  [all_data_2020_copy_2  .ball > 15 ]

        runs_first_six_overs = all_data_2020_copy.groupby(["batting_team"])["total_runs"].sum() \
        .reset_index(name="runs_first_six_overs").sort_values( by = 'runs_first_six_overs',ascending = False) 





        balls_faced_first_six_overs = all_data_2020_copy  .groupby(["batting_team"])["ball"].count() \
        .reset_index(name="balls_faced_first_six_overs").sort_values( by = 'balls_faced_first_six_overs',ascending = False) 






        runs_first_six_overs["runrate_first_six_overs"] = runs_first_six_overs["runs_first_six_overs"].div(balls_faced_first_six_overs['balls_faced_first_six_overs'].values,axis=0).apply(lambda x: x*6)


        run_rate_first_six_overs = runs_first_six_overs

        all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_first_six_overs, how="left")

        all_data_2020_logReg = all_data_2020_logReg.drop("runs_first_six_overs",axis=1)

        all_data_2020_logReg

        # Wickets First Six Overs 



        wickets_lost_six_overs = all_data_2020_copy.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
        .reset_index( name = 'wickets_lost_six_overs').sort_values( by = 'wickets_lost_six_overs',ascending = False) 



        wickets_lost_six_overs["avg_wickets_lost_six_overs"] = wickets_lost_six_overs["wickets_lost_six_overs"].div(matches['matches'].values,axis=0)


        wickets_lost_six_overs = wickets_lost_six_overs.drop("wickets_lost_six_overs",axis=1)

        all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_six_overs, how="left")

        all_data_2020_logReg

        # RR Last 5 Overs


        runs_last_five_overs = all_data_2020_copy_2 .groupby(["batting_team"])["total_runs"].sum() \
        .reset_index(name="runs_last_five_overs").sort_values( by = 'runs_last_five_overs',ascending = False) 





        balls_faced_last_five_overs = all_data_2020_copy_2  .groupby(["batting_team"])["ball"].count() \
        .reset_index(name="balls_faced_last_five_overs").sort_values( by = 'balls_faced_last_five_overs',ascending = False) 





        runs_last_five_overs

        balls_faced_last_five_overs

        runs_last_five_overs["runrate_last_five_overs"] = runs_last_five_overs["runs_last_five_overs"].div(balls_faced_last_five_overs['balls_faced_last_five_overs'].values,axis=0).apply(lambda x: x*6)


        run_rate_last_five_overs = runs_last_five_overs

        all_data_2020_logReg = all_data_2020_logReg.merge(run_rate_last_five_overs, how="left")

        all_data_2020_logReg = all_data_2020_logReg.drop("runs_last_five_overs",axis=1)

        all_data_2020_logReg

        # Wickets Lost Last 5 Overs

        wickets_lost_last_five_overs = all_data_2020_copy_2.groupby(["batting_team"])["player_dismissed"].apply(lambda x: (x!='0').sum())\
        .reset_index( name = 'wickets_lost_last_five_overs').sort_values( by = 'wickets_lost_last_five_overs',ascending = False) 

        wickets_lost_last_five_overs["avg_wickets_lost_last_five_overs"] = wickets_lost_last_five_overs["wickets_lost_last_five_overs"].div(matches['matches'].values,axis=0)

        wickets_lost_last_five_overs = wickets_lost_last_five_overs.drop("wickets_lost_last_five_overs",axis=1)

        all_data_2020_logReg = all_data_2020_logReg.merge(wickets_lost_last_five_overs, how="left")

        all_data_2020_logReg


        batsman_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Batsman.csv')
        bowler_pca_2020 = pd.read_csv('/Users/39388/Documents/PCA_2020_Bowlers.csv')

        all_data_2020_logReg= all_data_2020_logReg.rename(columns={"batting_team": "team"})

        all_data_2020_logReg = all_data_2020_logReg.merge(batsman_pca_2020, how="left")

        all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "batsman_PCA"})

        all_data_2020_logReg = all_data_2020_logReg.merge(bowler_pca_2020, how="left")

        all_data_2020_logReg= all_data_2020_logReg.rename(columns={"PC1": "bowler_PCA"})

        data_20_info = all_data_2020_logReg.append((data_20_info), ignore_index=True, on_bad_lines='skip')

IndexError: Replacement index 1 out of range for positional args tuple

In [3]:
import pandas as pd
import math
import numpy as np

In [4]:
        test = pd.DataFrame()
        test = pd.read_csv('/Users/39388/Downloads/psl_csv2/psl_csv_2020/1211655_info.csv',  on_bad_lines='skip')

In [5]:
test =test.transpose()

In [6]:
test. columns=test. iloc[0]

In [21]:
test = test[['winner','match_number']]
test = test.iloc[1:]
test

version         winner match_number
2.1.0    Karachi Kings           14

In [24]:
        data_2020_temp = pd.DataFrame()
        
        data_2020_temp = pd.read_csv('/Users/39388/Downloads/psl_csv2/psl_csv_2020/1211655_info.csv', on_bad_lines='skip')
                                     
        data_2020_temp = data_2020_temp.transpose()   
                                     
        data_2020_temp.columns=  data_2020_temp. iloc[0]
                                     
        data_2020_temp = data_2020_temp[['winner','match_number']]
                                     
        data_2020_temp = data_2020_temp.iloc[1:]

In [35]:
import os

path = '/Users/39388/Downloads/psl_csv2/psl_csv_2020/' #replace with the relative folder to where the files are contained

cwd = os.path.relpath(path) 
files = os.listdir(cwd)  

all_matches_list_2020 = pd.DataFrame()
data = pd.DataFrame()
all_data_2020_logReg = pd.DataFrame()


data_2020_info = pd.DataFrame()

for file in files:
    if file.endswith('info.csv'):
        data_2020_temp = pd.DataFrame()
        data_2020_temp = pd.read_csv('{}{}'.format(((path,file))),ignore_index=True,on_bad_lines='skip')
        data_2020_temp = data_2020_temp.transpose()
        data_2020_temp.columns=  data_2020_temp. iloc[0]

        data_2020_temp = data_2020_temp[['winner','match_number']]

        data_2020_temp = data_2020_temp.iloc[1:]

        data_2020_info = data_2020_info.append((data_2020_temp), ignore_index=True, on_bad_lines='skip')

        data_2020_temp = pd.DataFrame()

IndexError: Replacement index 1 out of range for positional args tuple

In [1]:
import pandas as pd
import statsmodels.formula.api as smf

In [2]:
cricket_2020 = pd.read_csv("/Users/39388/Downloads/finalDelivery/ProcessedDataSet/2020ProcessedData.csv")

In [7]:
# 
import statsmodels.api as sm
import pandas as pd 
  
# loading the training dataset 
df1 = pd.read_csv('/Users/39388/Downloads/2020ProcessedData1.csv', index_col = 0)
df1 = df1.dropna()
df1.drop(index = [55,56], inplace = True)
# defining the dependent and independent variables
Xtrain = df1[["runrate_first_six_over","wickets_lost_first_six","runrate_last_five_over","wickets_lost_last_five","batsman_PCA","bowler_PCA","toss_win","stddev_batsman","strike_rotation","stddev_bowler"]]
ytrain = df1[['match_win']]
   
# building the model and fitting the data
log_reg = sm.Logit(ytrain, Xtrain).fit()

Optimization terminated successfully.
         Current function value: 0.477610
         Iterations 7

In [8]:

df1.tail(13)

,team,match_id,runrate_first_six_over,wickets_lost_first_six,runrate_last_five_over,wickets_lost_last_five,batsman_PCA,bowler_PCA,toss_win,match_win,strike_rotation,stddev_batsman,stddev_bowler
48,Peshawar Zalmi,1211668.0,5.0,2.0,10.0,5.0,0.068793,0.179808,1.0,0.0,89.0,1.824114,2.010748
49,Islamabad United,1211669.0,8.0,1.0,7.0,2.0,-0.827038,0.770459,0.0,0.0,85.0,1.121183,1.388223
50,Karachi Kings,1211669.0,10.0,2.0,9.0,3.0,2.358933,0.096091,1.0,1.0,61.0,2.246046,0.486607
51,Multan Sultans,1211670.0,6.0,2.0,15.0,1.0,-0.502300,-0.270579,0.0,0.0,85.0,0.428105,1.684230
52,Lahore Qalandars,1211670.0,12.0,0.0,10.0,0.0,-0.510316,0.000000,1.0,1.0,49.0,1.102027,0.000000
53,Karachi Kings,1211671.0,6.0,2.0,9.0,2.0,2.795073,0.449906,1.0,0.0,83.0,2.086672,1.301850
54,Quetta Gladiators,1211671.0,9.0,1.0,7.0,3.0,-0.401480,0.122498,0.0,1.0,48.0,1.712828,1.015568
57,Peshawar Zalmi,1211673.0,6.0,2.0,10.0,4.0,0.889420,-1.006939,0.0,0.0,80.0,2.679053,0.388083
58,Lahore Qalandars,1211673.0,6.0,3.0,11.0,1.0,-0.328489,0.132293,1.0,1.0,75.0,1.109202,0.449513
59,Lahore Qalandars,1211675.0,9.0,2.0,13.0,1.0,-0.328489,-0.937338,0.0,1.0,71.0,1.109202,0.678144
60,Multan Sultans,1211675.0,10.0,1.0,8.0,4.0,-0.541604,-0.235257,1.0,0.0,83.0,0.376948,1.842952
61,Lahore Qalandars,1231146.0,6.0,0.0,8.0,3.0,-0.328489,0.879596,1.0,0.0,78.0,1.109202,1.497041
62,Karachi Kings,1231146.0,7.0,1.0,8.0,3.0,1.447973,-1.006939,0.0,1.0,91.0,2.145062,0.388083

In [17]:
print(log_reg.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:              match_win   No. Observations:                   61
Model:                          Logit   Df Residuals:                       51
Method:                           MLE   Df Model:                            9
Date:                Wed, 07 Sep 2022   Pseudo R-squ.:                  0.3108
Time:                        21:51:06   Log-Likelihood:                -29.134
converged:                       True   LL-Null:                       -42.274
Covariance Type:            nonrobust   LLR p-value:                  0.001839
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
runrate_first_six_over     0.1960      0.141      1.390      0.164      -0.080       0.472
wickets_lost_first_six    -0.6126      0.391     -1.568      0.117      -1.378       0.153
runrate_last_five_over     0.1810      0.123      1.475      0.140      -0.060       0.422
wickets_lost_last_five    -0.7304      0.319     -2.292      0.022      -1.355      -0.106
batsman_PCA               -0.3476      0.375     -0.928      0.354      -1.082       0.387
bowler_PCA                -0.7860      0.642     -1.224      0.221      -2.045       0.472
toss_win                   1.2402      0.689      1.799      0.072      -0.111       2.591
stddev_batsman             0.4418      0.587      0.753      0.452      -0.709       1.593
strike_rotation           -0.0176      0.018     -0.957      0.338      -0.054       0.018
stddev_bowler             -0.5752      0.516     -1.115      0.265      -1.586       0.436
==========================================================================================

In [9]:


import statsmodels.api as sm
import pandas as pd 
  
# loading the training dataset 
df2 = pd.read_csv('/Users/39388/Downloads/2021ProcessedData1.csv', index_col = 0)
df2 = df2.dropna()
# defining the dependent and independent variables
Xtrain = df2[["runrate_first_six_over","wickets_lost_first_six","runrate_last_five_over","wickets_lost_last_five","batsman_PCA","bowler_PCA","toss_win","stddev_batsman","strike_rotation","stddev_bowler"]]
ytrain = df2[['match_win']]
   
# building the model and fitting the data
log_reg = sm.Logit(ytrain, Xtrain).fit()

Optimization terminated successfully.
         Current function value: 0.399432
         Iterations 7

In [10]:
print(log_reg.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:              match_win   No. Observations:                   68
Model:                          Logit   Df Residuals:                       58
Method:                           MLE   Df Model:                            9
Date:                Thu, 08 Sep 2022   Pseudo R-squ.:                  0.4237
Time:                        20:48:12   Log-Likelihood:                -27.161
converged:                       True   LL-Null:                       -47.134
Covariance Type:            nonrobust   LLR p-value:                 7.774e-06
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
runrate_first_six_over     0.1287      0.155      0.829      0.407      -0.176       0.433
wickets_lost_first_six    -0.4077      0.320     -1.273      0.203      -1.035       0.220
runrate_last_five_over     0.1172      0.126      0.933      0.351      -0.129       0.363
wickets_lost_last_five    -0.9766      0.309     -3.160      0.002      -1.582      -0.371
batsman_PCA               -0.3509      0.463     -0.757      0.449      -1.259       0.557
bowler_PCA                -0.0178      0.567     -0.031      0.975      -1.129       1.094
toss_win                   2.2573      0.735      3.073      0.002       0.817       3.697
stddev_batsman             0.4849      0.755      0.642      0.521      -0.995       1.965
strike_rotation           -0.0179      0.030     -0.593      0.553      -0.077       0.041
stddev_bowler              0.3014      0.525      0.575      0.566      -0.727       1.329
==========================================================================================

In [11]:


import statsmodels.api as sm
import pandas as pd 
  
# loading the training dataset 
df3 = pd.read_csv('/Users/39388/Downloads/2022ProcessedData1.csv', index_col = 0)
df3 = df3.dropna()
# defining the dependent and independent variables
Xtrain = df3[["runrate_first_six_over","wickets_lost_first_six","runrate_last_five_over","wickets_lost_last_five","batsman_PCA","bowler_PCA","toss_win","stddev_batsman","strike_rotation","stddev_bowler"]]
ytrain = df3[['match_win']]
   
# building the model and fitting the data
log_reg = sm.Logit(ytrain, Xtrain).fit()

Optimization terminated successfully.
         Current function value: 0.308228
         Iterations 8

In [12]:
print(log_reg.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:              match_win   No. Observations:                   68
Model:                          Logit   Df Residuals:                       58
Method:                           MLE   Df Model:                            9
Date:                Thu, 08 Sep 2022   Pseudo R-squ.:                  0.5550
Time:                        20:48:12   Log-Likelihood:                -20.959
converged:                       True   LL-Null:                       -47.105
Covariance Type:            nonrobust   LLR p-value:                 3.984e-08
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
runrate_first_six_over     0.4868      0.224      2.176      0.030       0.048       0.925
wickets_lost_first_six    -0.4469      0.482     -0.926      0.354      -1.393       0.499
runrate_last_five_over    -0.1080      0.165     -0.656      0.512      -0.431       0.215
wickets_lost_last_five    -0.9332      0.362     -2.576      0.010      -1.643      -0.223
batsman_PCA                1.3738      0.864      1.591      0.112      -0.319       3.067
bowler_PCA                -2.2148      1.004     -2.206      0.027      -4.182      -0.247
toss_win                   1.6208      1.008      1.608      0.108      -0.355       3.597
stddev_batsman             0.8209      2.156      0.381      0.703      -3.406       5.048
strike_rotation           -0.0107      0.037     -0.285      0.776      -0.084       0.063
stddev_bowler             -0.5747      1.154     -0.498      0.618      -2.836       1.686
==========================================================================================

In [13]:
df1.concat(df2)

AttributeError: 'DataFrame' object has no attribute 'concat'

In [14]:
df4 = df1.append(df2)

/var/folders/z6/xbk9c3917w983ys4yhfxzkk9wvnf95/T/ipykernel_19681/3478716966.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df4 = df1.append(df2)

In [15]:
df5 = df4.append(df3)

/var/folders/z6/xbk9c3917w983ys4yhfxzkk9wvnf95/T/ipykernel_19681/2796519502.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5 = df4.append(df3)

In [16]:
df5

,team,match_id,runrate_first_six_over,wickets_lost_first_six,runrate_last_five_over,wickets_lost_last_five,batsman_PCA,bowler_PCA,toss_win,match_win,strike_rotation,stddev_batsman,stddev_bowler
0,Islamabad United,1211642.0,9.0,2.0,9.0,6.0,0.112789,-0.191240,0.0,0.0,79.0,1.613872,1.494731
1,Quetta Gladiators,1211642.0,6.0,3.0,9.0,3.0,-0.401480,0.044789,1.0,1.0,67.0,1.712828,0.530870
2,Karachi Kings,1211643.0,8.0,1.0,11.0,2.0,2.358933,0.275947,0.0,1.0,88.0,2.246046,0.419501
3,Peshawar Zalmi,1211643.0,8.0,2.0,13.0,2.0,0.865969,0.232708,1.0,0.0,105.0,1.376433,0.759959
4,Lahore Qalandars,1211644.0,10.0,2.0,7.0,3.0,-0.328489,-0.058016,0.0,0.0,54.0,1.109202,1.860303
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Islamabad United,1293031.0,9.0,1.0,12.0,2.0,-0.294828,0.692007,0.0,1.0,74.0,1.681994,0.802737
64,Lahore Qalandars,1293032.0,6.0,2.0,11.0,2.0,1.136496,0.700885,1.0,1.0,83.0,2.110266,1.114360
65,Islamabad United,1293032.0,8.0,4.0,6.0,5.0,-0.053311,0.366746,0.0,0.0,85.0,1.626418,1.838088
66,Lahore Qalandars,1293033.0,6.0,3.0,15.0,1.0,1.136496,1.074225,1.0,1.0,79.0,2.110266,1.114771
67,Multan Sultans,1293033.0,8.0,2.0,8.0,5.0,1.854690,0.366746,0.0,0.0,76.0,2.037226,1.838088

In [29]:
df5 = df5.dropna()
# defining the dependent and independent variables
Xtrain = df5[["runrate_first_six_over","wickets_lost_first_six","runrate_last_five_over","wickets_lost_last_five","batsman_PCA","toss_win","bowler_PCA","stddev_batsman","strike_rotation","stddev_bowler"]]
ytrain = df5[['match_win']]
   
# building the model and fitting the data
log_reg = sm.Logit(ytrain, Xtrain).fit()

Optimization terminated successfully.
         Current function value: 0.453030
         Iterations 7

In [30]:
print(log_reg.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:              match_win   No. Observations:                  197
Model:                          Logit   Df Residuals:                      187
Method:                           MLE   Df Model:                            9
Date:                Thu, 08 Sep 2022   Pseudo R-squ.:                  0.3463
Time:                        20:50:47   Log-Likelihood:                -89.247
converged:                       True   LL-Null:                       -136.53
Covariance Type:            nonrobust   LLR p-value:                 1.972e-16
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
runrate_first_six_over     0.1760      0.080      2.194      0.028       0.019       0.333
wickets_lost_first_six    -0.5264      0.187     -2.817      0.005      -0.893      -0.160
runrate_last_five_over     0.0751      0.059      1.264      0.206      -0.041       0.192
wickets_lost_last_five    -0.7686      0.153     -5.007      0.000      -1.069      -0.468
batsman_PCA                0.0777      0.219      0.354      0.723      -0.352       0.507
toss_win                   1.3424      0.385      3.486      0.000       0.588       2.097
bowler_PCA                -0.8377      0.297     -2.821      0.005      -1.420      -0.256
stddev_batsman             0.4336      0.372      1.165      0.244      -0.296       1.163
strike_rotation           -0.0108      0.012     -0.900      0.368      -0.034       0.013
stddev_bowler              0.0378      0.302      0.125      0.900      -0.554       0.630
==========================================================================================

In [48]:
newpred = pd.DataFrame(df5.loc[[2]])

In [54]:
newpred = newpred.drop("match_win", 1)

/var/folders/z6/xbk9c3917w983ys4yhfxzkk9wvnf95/T/ipykernel_19681/2815984812.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  newpred = newpred.drop("match_win", 1)

ValueError: shapes (3,12) and (10,) not aligned: 12 (dim 1) != 10 (dim 0)

In [70]:
df = pd.read_csv('/Users/39388/Downloads/2022ProcessedData1.csv', index_col = 0)
  
# defining the dependent and independent variables
Xtest = df[["runrate_first_six_over","wickets_lost_first_six","runrate_last_five_over","wickets_lost_last_five","batsman_PCA","toss_win","bowler_PCA","stddev_batsman","strike_rotation","stddev_bowler"]]
ytest = df['match_win']
  
# performing predictions on the test datdaset
yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))
  
# comparing original and predicted values of y
print('Actual values', list(ytest.values))
print('Predictions :', prediction)

Actual values [0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0]
Predictions : [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [71]:

from sklearn.metrics import (confusion_matrix, 
                           accuracy_score)
  
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix :
 [[27  8]
 [ 7 26]]
Test accuracy =  0.7794117647058824

In [ ]:
import pandas as pd

df3 = pd.read_csv('PCA_2020_Bowlers.csv')
boundaries = pd.DataFrame()
boundaries =df3.groupby(['team']).agg(
    stddev_batsman = ('stddev_batsman','mean'),
    matches = ('match_id','count')
    
)
boundaries = boundaries.reset_index() 
boundaries
boundaries["team"] = ["Islamabad United","Karachi Kings","Lahore Qalandars","Multan Sultans","Peshawar Zalmi","Quetta Gladiators"]
boundaries = boundaries.rename(columns={'team': 'Team', 'stddev_batsman': 'Average Batter Standard Deviation'})

ax =boundaries.plot(x = 'Team', y = 'Average Batter Standard Deviation', kind='bar', rot=0,
                figsize=(10,4), # Figsize to make the plot larger
            title='Average Batter Standard Deviation 2022', # Adding a title to the top
            xlabel="Teams", # Adding a label on the xaxis
            ylabel="Average Batter Standard Deviation", # Adding a label on y axis
            fontsize='medium')